name: finvu_flutter_sdk
description: "A new Flutter plugin project."
version: 0.0.3
homepage: https://www.finvu.in/
publish_to: none

environment:
  sdk: ">=3.1.0 <4.0.0"
  flutter: ">=3.3.0"

dependencies:
  flutter:
    sdk: flutter
  plugin_platform_interface: ^2.0.2
  finvu_flutter_sdk_core:
    git:
      url: https://github.com/ReyLeonWing/finvu_flutter_sdk.git
      path: core
      ref: main

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.0
  pigeon: ^14.0.1

flutter:
  plugin:
    platforms:
      android:
        package: com.finvu.finvu_flutter_sdk
        pluginClass: FinvuFlutterSdkPlugin
      ios:
        pluginClass: FinvuFlutterSdkPlugin
